// List of slug paths that are static pages (not Firestore content)
// The [...slug] route will check this before attempting Firestore lookup
export const STATIC_PAGE_SLUGS = new Set([
    'about',
    'model',
    'senior-expert-council',
    'about/impact',
    'leadership',
    'expertise',
    'intelligence',
    'transformation',
    'innovation',
    'clients',
    'stories',
    'stories/impact',
    'stories/news',
    'stories/press-releases',
    'stories/press',
    'insights',
    'insights/insights',
    'insights/voices',
    'insights/publications',
    'insights/conferences',
    'contact',
    'cookies',
    'privacy',
    'quality-environment',
    'legal-notice',
    'compliance',
    'work',
    'events',
    'challenges',
    'academy',
])
