import InteriorPageLayout from '@/components/InteriorPageLayout'
import { getSidebar } from "@/lib/page-data"

export default function QualityEnvironmentPage({ lang }: { lang: string }) {
    const breadcrumb = lang === 'es' ? 'Contacto' : lang === 'it' ? 'Contatto' : 'Contact'
    const title = lang === 'es' ? 'Calidad y Medio Ambiente' : lang === 'it' ? 'Qualità e Ambiente' : 'Quality and Environment'

    return (
        <InteriorPageLayout
            breadcrumb={breadcrumb}
            title={title}
            sidebar={getSidebar("contact", lang)}
        >
            <div className="prose prose-sm max-w-none text-opinno-gray font-body leading-relaxed">
                <h2 className="text-xl font-bold font-display text-opinno-primary mb-4">
                    {lang === 'es' ? 'Política de Gestión de Calidad y Medio Ambiente' : lang === 'it' ? 'Politica di Gestione della Qualità e dell\'Ambiente' : 'Quality and Environmental Management Policy'}
                </h2>

                <p className="mb-6">
                    {lang === 'es'
                        ? 'Opinno, siendo su actividad la estrategia de innovación y transformación digital; transformación cultural y nuevas formas de trabajo; el diseño de productos, servicios y experiencia del cliente; la gestión de comunidades de innovación; los contenidos de innovación y tecnología; el diseño y desarrollo de soluciones digitales; y el prototipado de soluciones digitales, dispone de un sistema de gestión de calidad y medio ambiente documentado que se concreta en los siguientes puntos:'
                        : lang === 'it'
                            ? 'Opinno, la cui attività comprende la strategia di innovazione e trasformazione digitale; trasformazione culturale e nuove forme di lavoro; progettazione di prodotti, servizi ed esperienza del cliente; gestione di comunità di innovazione; contenuti di innovazione e tecnologia; progettazione e sviluppo di soluzioni digitali; e prototipazione di soluzioni digitali, dispone di un sistema di gestione della qualità e dell\'ambiente documentato che si concretizza nei seguenti punti:'
                            : 'Opinno, whose activity encompasses innovation strategy and digital transformation; cultural transformation and new forms of work; the design of products, services and customer experience; the management of innovation communities; innovation and technology content; the design and development of digital solutions; and the prototyping of digital solutions, has a documented quality and environmental management system specified in the following points:'}
                </p>

                <ul className="list-disc ml-6 space-y-3 mb-8">
                    <li>
                        {lang === 'es'
                            ? 'Cumplimiento de los requisitos legales y técnicos, así como cualquier otro que se suscriba a los aspectos ambientales que genera por su actividad laboral.'
                            : lang === 'it'
                                ? 'Conformità ai requisiti legali e tecnici, nonché a qualsiasi altro requisito sottoscritto relativamente agli aspetti ambientali generati dalla propria attività lavorativa.'
                                : 'Compliance with legal and technical requirements, as well as any other requirements subscribed to regarding the environmental aspects generated by its work activity.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'Compromiso de perseguir la prevención de la contaminación, la protección del medio ambiente, así como cualquier otro específico relevante para el contexto de la Organización.'
                            : lang === 'it'
                                ? 'Impegno a perseguire la prevenzione dell\'inquinamento, la protezione dell\'ambiente, nonché qualsiasi altro impegno specifico rilevante per il contesto dell\'Organizzazione.'
                                : 'Commitment to pursuing the prevention of pollution, protection of the environment, as well as any other specific commitment relevant to the context of the Organization.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'Orientar las actividades y decisiones de la empresa para satisfacer las necesidades y expectativas de los clientes.'
                            : lang === 'it'
                                ? 'Orientare le attività e le decisioni dell\'azienda per soddisfare le esigenze e le aspettative dei clienti.'
                                : 'Orienting the activities and decisions of the company to meet the needs and expectations of customers.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'Asegurar la calidad y la correcta gestión ambiental de todas las actividades con el fin de garantizar los servicios prestados a los clientes.'
                            : lang === 'it'
                                ? 'Garantire la qualità e la corretta gestione ambientale di tutte le attività al fine di garantire i servizi forniti ai clienti.'
                                : 'Ensure the quality and correct environmental management of all activities in order to guarantee the services provided to customers.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'Promover la autonomía e iniciativa del personal para contribuir más eficazmente a la consecución de los objetivos de Opinno.'
                            : lang === 'it'
                                ? 'Promuovere l\'autonomia e l\'iniziativa del personale per contribuire più efficacemente al raggiungimento degli obiettivi di Opinno.'
                                : 'Promote the autonomy and initiative of staff to contribute more effectively to achieving the objectives of Opinno.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'Mantener un espíritu de mejora continua de la eficacia en todas las actividades relacionadas con el sistema y los clientes.'
                            : lang === 'it'
                                ? 'Mantenere uno spirito di miglioramento continuo dell\'efficacia in tutte le attività relative al sistema e ai clienti.'
                                : 'Maintain a spirit of continuous improvement of effectiveness in all activities related to the system and customers.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'La dirección y el personal de Opinno comparten y entienden este sistema de gestión como una forma de trabajo para todas y cada una de sus actividades.'
                            : lang === 'it'
                                ? 'La direzione e il personale di Opinno condividono e comprendono questo sistema di gestione come un modo di lavorare per ciascuna delle sue attività.'
                                : 'The management and staff of Opinno share and understand this management system as a form of work for each and every one of its activities.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'Esta política de gestión de calidad y medio ambiente ha sido comunicada a todo el personal de la empresa, así como a todo el personal y organización que trabaja en nombre de Opinno, y es entendida, aplicada y mantenida al día en todos los niveles de la organización. Regularmente se realiza un seguimiento de su eficacia y cumplimiento.'
                            : lang === 'it'
                                ? 'Questa politica di gestione della qualità e dell\'ambiente è stata comunicata a tutto il personale dell\'azienda, nonché a tutto il personale e alle organizzazioni che lavorano per conto di Opinno, ed è compresa, applicata e mantenuta aggiornata a tutti i livelli dell\'organizzazione. Regolarmente viene effettuato un monitoraggio della sua efficacia e conformità.'
                                : 'This quality and environmental management policy has been communicated to all company staff, as well as to all personnel and organizations that work on behalf of Opinno, and is understood, applied and maintained up to date at all levels of the organization. Regularly, a monitoring of its effectiveness and compliance is carried out.'}
                    </li>
                    <li>
                        {lang === 'es'
                            ? 'Esta Política de Gestión Integrada está disponible para cualquier persona u organización que esté interesada en conocerla.'
                            : lang === 'it'
                                ? 'Questa Politica di Gestione Integrata è disponibile per qualsiasi persona o organizzazione interessata a conoscerla.'
                                : 'This Integrated Management Policy is available to any person or organization that is interested in knowing it.'}
                    </li>
                </ul>

                <p className="mb-6">
                    {lang === 'es'
                        ? 'La dirección establece y revisa sus objetivos y metas ambientales y de calidad para cada una de las áreas, teniendo como marco de referencia la política definida, fijando responsabilidades en su consecución, estableciendo los criterios de actuación y asignando los recursos necesarios, con el fin de alcanzar los objetivos y metas genéricos de la política de gestión integrada.'
                        : lang === 'it'
                            ? 'La direzione stabilisce e rivede i propri obiettivi e traguardi ambientali e di qualità per ciascuna delle aree, avendo come quadro di riferimento la politica definita, fissando le responsabilità nel loro raggiungimento, stabilendo i criteri di azione e assegnando le risorse necessarie, al fine di raggiungere gli obiettivi e i traguardi generici della politica di gestione integrata.'
                            : 'The management establishes and reviews its environmental and quality objectives and goals for each of the areas, having the defined policy as a framework of reference, setting responsibilities for their attainment, establishing action criteria and assigning the necessary resources, in order to achieve the generic objectives and goals of the integrated management policy.'}
                </p>

                <div className="mt-10 pt-6 border-t border-opinno-border">
                    <p className="italic text-sm text-opinno-gray">
                        {lang === 'es'
                            ? 'FDO.: La Dirección'
                            : lang === 'it'
                                ? 'Firmato: La Direzione'
                                : 'Signed: The Management'}
                    </p>
                    <p className="text-sm text-opinno-gray mt-2">
                        {lang === 'es'
                            ? 'Aprobado por la dirección en Madrid, 1 de septiembre de 2019.'
                            : lang === 'it'
                                ? 'Approvato dalla direzione a Madrid, 1 settembre 2019.'
                                : 'Approved by management in Madrid, September 1, 2019.'}
                    </p>
                </div>
            </div>
        </InteriorPageLayout>
    )
}
